import type { Metadata } from "next";
import "@fortawesome/fontawesome-free/css/all.min.css";

import "./globals.css";
import NavbarComponent from "@/components/navbar/Navbar";
import "swiper/css";
import "swiper/css/pagination";
import FooterComponent from "@/components/footer/footer";

import ScrollAndContactButtons from "@/components/ui-section/ScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NavbarComponent />
        {children}

        <FooterComponent />
        <ScrollAndContactButtons />
      </body>
    </html>
  );
}
